export const abilityEffectsMap = {
    'autoAttack': 'slash',
    'default': 'fireball',
    'heal': 'heal',

    '/abilities/fireball': "fireball",
    '/abilities/firestorm': "lavaPlume",
    '/abilities/flame_blast': "lavaPlume",
    '/abilities/smoke_burst': "fireball",
    '/abilities/aqua_arrow': "water",
    '/abilities/frost_surge': "iceBlast",
    '/abilities/ice_spear': "iceBlast",
    '/abilities/mana_spring': "water",
    '/abilities/water_strike': "water",
    '/abilities/entangle': "nature",
    '/abilities/natures_veil': "nature",
    '/abilities/toxic_pollen': "poisonDust",
    '/abilities/penetrating_shot': "range",
    '/abilities/pestilent_shot': "range",
    '/abilities/steady_shot': "range",
    '/abilities/quick_shot': "range",
    '/abilities/rain_of_arrows': "range",
    '/abilities/silencing_shot': "range",
    '/abilities/crippling_slash': "slash",
    '/abilities/penetrating_strike': "slash",
    '/abilities/impale': "thrust",
    '/abilities/maim': "slash",
    '/abilities/poke': "thrust",
    '/abilities/puncture': "thrust",
    '/abilities/scratch': "slash",
    '/abilities/smack': "slash",
    '/abilities/sweep': "slash",
    '/abilities/stunning_blow': "slash",
}